SET NOCOUNT ON;
;WITH m(Code, NameEn) AS (
    SELECT * FROM (VALUES
        -- 111x Land
        ('1111', N'Agricultural Land'),
        ('1112', N'Construction Land'),
        ('1113', N'Open Land'),
        -- 112x Buildings, Constructions & Roads
        ('1121', N'Buildings'),
        ('1122', N'Warehouses, Tanks & Silos'),
        ('1123', N'Wells, Mines & Quarries'),
        ('1125', N'Dams & Canals'),
        ('1126', N'Floating Structures'),
        ('1127', N'Roads & Bridges'),
        ('1128', N'Transport Facilities'),
        ('1129', N'Other Facilities'),
        -- 114x Vehicles & Transport
        ('1141', N'Motor Vehicles'),
        ('1142', N'Rail Transport'),
        ('1143', N'River Transport'),
        ('1144', N'Maritime Transport'),
        ('1145', N'Air Transport'),
        ('1146', N'Oil & Gas Pipelines'),
        -- 115x Tools & Dies
        ('1151', N'Tools'),
        ('1152', N'Dies'),
        ('1153', N'Tents & Covers'),
        -- 116x Furniture & Office Equipment
        ('1161', N'Furniture'),
        ('1162', N'Air-conditioning & Cooling Equipment'),
        ('1163', N'Computers'),
        ('1164', N'Calculators, Typewriters & Copiers'),
        ('1165', N'Office Tools & Devices'),
        ('1166', N'Curtains & Soft Furnishings'),
        ('1167', N'Books & Scientific References'),
        -- 117x Plants & Animals
        ('1171', N'Plants'),
        ('1172', N'Animals'),
        -- 118x Deferred Revenue Expenditures
        ('1181', N'Incorporation Expenses'),
        ('1182', N'Pre-operating Expenses'),
        ('1183', N'Exploration & Survey Expenses'),
        ('1184', N'Research & Trial Expenses'),
        ('1185', N'Intangible Fixed Assets'),
        ('1186', N'Decoration, Fittings & Partitions'),
        ('1187', N'Miscellaneous Deferred Expenses'),
        -- 121x – 128x (Projects Under Construction — mirror of 111x–118x)
        ('1211', N'Agricultural Land (UC)'),
        ('1212', N'Construction Land (UC)'),
        ('1213', N'Open Land (UC)'),
        ('1221', N'Buildings (UC)'),
        ('1222', N'Warehouses, Tanks & Silos (UC)'),
        ('1223', N'Residential Facilities (UC)'),
        ('1224', N'Wells, Mines & Quarries (UC)'),
        ('1225', N'Dams & Canals (UC)'),
        ('1226', N'Floating Structures (UC)'),
        ('1227', N'Roads & Bridges (UC)'),
        ('1228', N'Transport Facilities (UC)'),
        ('1229', N'Other Facilities (UC)'),
        ('1241', N'Motor Vehicles (UC)'),
        ('1242', N'Rail Transport (UC)'),
        ('1243', N'River Transport (UC)'),
        ('1244', N'Maritime Transport (UC)'),
        ('1245', N'Air Transport (UC)'),
        ('1246', N'Oil & Gas Pipelines (UC)'),
        ('1251', N'Tools (UC)'),
        ('1252', N'Dies (UC)'),
        ('1253', N'Tents & Covers (UC)'),
        ('1261', N'Furniture (UC)'),
        ('1262', N'Air-conditioning & Cooling Equipment (UC)'),
        ('1263', N'Computers (UC)'),
        ('1264', N'Calculators, Typewriters & Copiers (UC)'),
        ('1265', N'Office Tools & Devices (UC)'),
        ('1266', N'Curtains & Soft Furnishings (UC)'),
        ('1267', N'Books & Scientific References (UC)'),
        ('1271', N'Plants (UC)'),
        ('1272', N'Animals (UC)'),
        ('1281', N'Incorporation Expenses (UC)'),
        ('1282', N'Pre-operating Expenses (UC)'),
        ('1283', N'Exploration & Survey Expenses (UC)'),
        ('1284', N'Research & Trial Expenses (UC)'),
        ('1285', N'Intangible Fixed Assets (UC)'),
        ('1286', N'Decoration, Fittings & Partitions (UC)'),
        ('1287', N'Miscellaneous Deferred Expenses (UC)'),
        ('1291', N'Advance Payments'),
        ('1292', N'Letters of Credit for Fixed Assets'),
        -- 134x Packaging
        ('1341', N'Consumable Packaging Materials Warehouse'),
        ('1342', N'Circulating Packaging Materials Warehouse'),
        -- 135x Miscellaneous
        ('1351', N'Supplies & Consumables Warehouse'),
        ('1352', N'Stationery Warehouse'),
        ('1353', N'Educational Books Warehouse'),
        ('1354', N'Scrap & Consumables Warehouse'),
        ('1355', N'Worker Equipment Warehouse'),
        -- 136x Production
        ('1361', N'Finished Production Warehouse'),
        ('1362', N'Work-in-Progress Warehouse'),
        -- 138x L/Cs
        ('1381', N'Material Purchase L/Cs'),
        ('1382', N'L/Cs for Third Parties'),
        -- 139x
        ('1391', N'Goods at Third Parties'),
        -- 141x – 142x Loans Granted
        ('1411', N'Long-term Loans — Socialist Sector'),
        ('1412', N'Long-term Loans — Cooperative Sector'),
        ('1413', N'Long-term Loans — Mixed Sector'),
        ('1414', N'Long-term Loans — Private Sector'),
        ('1415', N'Long-term Loans — Foreign'),
        ('1421', N'Short-term Loans — Socialist Sector'),
        ('1422', N'Short-term Loans — Cooperative Sector'),
        ('1423', N'Short-term Loans — Mixed Sector'),
        ('1424', N'Short-term Loans — Private Sector'),
        ('1425', N'Short-term Loans — Foreign'),
        -- 151x – 152x Investments
        ('1511', N'Long-term Investments — Socialist Sector'),
        ('1512', N'Long-term Investments — Cooperative Sector'),
        ('1513', N'Long-term Investments — Mixed Sector'),
        ('1514', N'Long-term Investments — Private Sector'),
        ('1515', N'Long-term Investments — Foreign'),
        ('1521', N'Short-term Investments — Socialist Sector'),
        ('1522', N'Short-term Investments — Cooperative Sector'),
        ('1523', N'Short-term Investments — Mixed Sector'),
        ('1524', N'Short-term Investments — Private Sector'),
        ('1525', N'Short-term Investments — Foreign'),
        -- 161x Customers
        ('1611', N'Customers'),
        ('1612', N'Customers — Cooperative Sector'),
        ('1613', N'Customers — Mixed Sector'),
        ('1614', N'Customers — Private Sector'),
        ('1615', N'Customers — Foreign'),
        -- 162x Notes Receivable
        ('1621', N'Notes Receivable — Socialist Sector'),
        ('1622', N'Notes Receivable — Cooperative Sector'),
        ('1623', N'Notes Receivable — Mixed Sector'),
        ('1624', N'Notes Receivable — Private Sector'),
        ('1625', N'Notes Receivable — Foreign'),
        ('1626', N'Notes Receivable for Collection'),
        -- 163x Current Accounts
        ('1631', N'Debit Current Accounts — Within Organization'),
        ('1632', N'Debit Current Accounts — Within Facility'),
        -- 1652
        ('1652', N'Non-Current Activity Receivables'),
        -- 166x Miscellaneous
        ('1661', N'Deposits with Others'),
        ('1662', N'Accrued Revenue'),
        ('1663', N'Prepaid Expenses'),
        ('1664', N'Compensation Claims'),
        ('1665', N'Cash & Inventory Variances'),
        -- 167x Advances
        ('1671', N'Activity-purpose Advances'),
        ('1672', N'Employee Advances'),
        ('1673', N'Marriage Advances'),
        -- 181x Cash on Hand
        ('1811', N'Head Office Cash Box'),
        ('1812', N'Branch Cash Boxes'),
        -- 183x Banks
        ('1831', N'Banks'),
        ('1832', N'Payment Companies'),
        -- 185x Checks
        ('1851', N'Checks & Remittances in Collection'),
        ('1852', N'Remittances in Transit'),
        ('1853', N'Rejected Checks & Remittances'),
        -- 192x Commitments
        ('1921', N'Received Letters of Credit'),
        ('1922', N'Counter Issued Letters of Credit'),
        ('1923', N'Received Letters of Guarantee'),
        ('1924', N'Counter Issued Letters of Guarantee'),
        ('1925', N'Contracts'),
        -- 194x Result Accounts
        ('1941', N'Computed Rental Variance'),
        ('1942', N'Computed Interest Variance'),
        ('1943', N'Finished Production Inventory Valuation Variance'),
        ('1944', N'Resale Goods Inventory Valuation Variance'),
        -- 211x – 212x Capital
        ('2111', N'Previously Paid Capital'),
        -- 221x Capital Reserves
        ('2211', N'Expansion Reserve'),
        ('2212', N'Fixed Assets Price Increase Reserve'),
        ('2213', N'Capital Gains Reserve'),
        ('2217', N'Bonus Shares Reserve'),
        -- 231x Provisions
        ('2312', N'Building & Roads Depreciation Provision'),
        ('2313', N'Machinery & Equipment Depreciation Provision'),
        ('2314', N'Vehicle Depreciation Provision'),
        ('2315', N'Tools & Dies Depreciation Provision'),
        ('2316', N'Furniture & Office Equipment Depreciation Provision'),
        -- 241x – 242x Loans Received
        ('2411', N'Long-term Loans from Socialist Sector'),
        ('2412', N'Long-term Loans from Cooperative Sector'),
        ('2413', N'Long-term Loans from Mixed Sector'),
        ('2414', N'Long-term Loans from Private Sector'),
        ('2415', N'Long-term Loans from Foreign'),
        ('2421', N'Short-term Loans from Socialist Sector'),
        ('2422', N'Short-term Loans from Cooperative Sector'),
        ('2423', N'Short-term Loans from Mixed Sector'),
        ('2424', N'Short-term Loans from Private Sector'),
        ('2425', N'Short-term Loans from Foreign'),
        -- 261x Suppliers
        ('2611', N'Suppliers — Socialist Sector'),
        ('2612', N'Suppliers — Cooperative Sector'),
        ('2613', N'Suppliers — Mixed Sector'),
        ('2614', N'Suppliers — Private Sector'),
        ('2615', N'Suppliers — Foreign'),
        -- 262x Notes Payable
        ('2621', N'Notes Payable — Socialist Sector'),
        ('2622', N'Notes Payable — Cooperative Sector'),
        ('2623', N'Notes Payable — Mixed Sector'),
        ('2624', N'Notes Payable — Private Sector'),
        ('2625', N'Notes Payable — Foreign'),
        -- 263x Current Accounts
        ('2631', N'Credit Current Accounts — Within Organization'),
        ('2632', N'Credit Current Accounts — Within Facility'),
        -- 264x Commitments
        ('2641', N'Advances Received'),
        ('2642', N'Completed Quantities'),
        -- 266x Miscellaneous Payables
        ('2661', N'Deposits Received'),
        ('2662', N'Revenue Received in Advance'),
        ('2663', N'Accrued Expenses'),
        ('2664', N'Salaries & Wages Payable'),
        ('2665', N'Returned Salaries & Wages'),
        ('2666', N'General Pension Directorate'),
        ('2667', N'Workers Pension & Social Security Institution'),
        -- 267x Deductions
        ('2671', N'Employee Deductions for Third Parties'),
        ('2672', N'Non-Employee Deductions for Third Parties'),
        -- 292x
        ('2921', N'Counter Approved Letters of Credit'),
        ('2922', N'Issued Letters of Credit'),
        ('2923', N'Counter Received Letters of Guarantee'),
        ('2924', N'Issued Letters of Guarantee'),
        ('2925', N'Counter Contracts'),
        -- 294x
        ('2941', N'Counter Computed Rental Variance'),
        ('2942', N'Counter Computed Interest Variance'),
        ('2943', N'Counter Finished Production Inventory Variance'),
        ('2944', N'Counter Resale Goods Inventory Variance'),
        -- 311x Employee Salaries
        ('3111', N'Salaries'),
        ('3112', N'Family Allowances'),
        ('3113', N'Overtime Wages'),
        ('3114', N'Incentive Bonuses'),
        ('3115', N'Professional & Technical Allowances'),
        ('3116', N'Compensatory Allowances'),
        ('3119', N'Other Allowances'),
        -- 312x Worker Wages
        ('3121', N'Wages'),
        ('3122', N'Family Allowances'),
        ('3123', N'Overtime Wages'),
        ('3124', N'Incentive Bonuses'),
        ('3125', N'Professional & Technical Allowances'),
        ('3126', N'Compensatory Allowances'),
        ('3127', N'Compensatory Allowances (2)'),
        ('3128', N'Incentive Bonuses (2)'),
        ('3129', N'Other Allowances'),
        -- 314x Employee Social Security
        ('3141', N'Facility Share in Pension'),
        ('3142', N'Employee Insurance'),
        ('3143', N'Employee Health Insurance'),
        -- 315x Worker Social Security
        ('3151', N'Facility Share in Social Security'),
        ('3152', N'Worker Insurance'),
        ('3153', N'Worker Health Insurance'),
        -- 322x Fuel & Oils
        ('3221', N'Petroleum Materials'),
        ('3222', N'Gas'),
        ('3223', N'Oils & Lubricants'),
        ('3224', N'Coal'),
        -- 324x Packaging
        ('3241', N'Consumable Packaging Materials'),
        ('3242', N'Circulating Packaging Materials'),
        -- 325x Miscellaneous Supplies
        ('3251', N'Supplies & Consumables'),
        ('3252', N'Stationery'),
        ('3253', N'Educational Books'),
        ('3254', N'Scrap & Consumables'),
        -- 326x Worker Equipment
        ('3261', N'Uniforms'),
        ('3262', N'Food Items'),
        ('3263', N'Medical Items'),
        -- 327x Utilities
        ('3271', N'Water'),
        ('3272', N'Electricity'),
        -- 331x Maintenance
        ('3312', N'Maintenance of Buildings & Roads'),
        ('3313', N'Maintenance of Machinery & Equipment'),
        ('3314', N'Maintenance of Vehicles'),
        ('3315', N'Maintenance of Tools & Dies'),
        ('3316', N'Maintenance of Furniture & Office Equipment'),
        -- 333x Advertising
        ('3331', N'Advertising & Publicity'),
        ('3332', N'Publishing & Printing'),
        ('3333', N'Hospitality'),
        ('3334', N'Exhibition Expenses'),
        ('3335', N'Ceremonies'),
        -- 334x Transport
        ('3341', N'Employee Transport'),
        ('3342', N'Goods Transport'),
        ('3343', N'Travel & Delegation'),
        ('3344', N'General Telecom'),
        -- 335x Rentals
        ('3352', N'Building Rentals'),
        ('3353', N'Machinery & Equipment Rentals'),
        ('3354', N'Vehicle Rentals'),
        ('3355', N'Tools & Dies Rentals'),
        ('3356', N'Furniture & Office Equipment Rentals'),
        -- 336x Other Service Expenses
        ('3361', N'Subscriptions & Memberships'),
        ('3362', N'Insurance Premiums'),
        ('3363', N'Bonuses to Non-employees for Services'),
        ('3364', N'Taxes & Fees Paid to Foreign Bodies'),
        ('3365', N'Legal Services'),
        ('3366', N'Banking Services'),
        ('3367', N'Training & Qualification'),
        ('3368', N'Audit Fees'),
        ('3369', N'Other Service Expenses'),
        -- 351x – 352x Purchases for Resale
        ('3511', N'Purchases of Goods for Resale'),
        ('3521', N'Purchases for Facility Account'),
        ('3522', N'Purchases for Third Parties'),
        ('3523', N'Commercial Samples Purchases'),
        ('3524', N'Damaged Goods Purchases'),
        -- 381x Transfer
        ('3811', N'Retirement Salaries'),
        ('3812', N'Social Bonuses'),
        -- 383x
        ('3831', N'Donations to Others'),
        ('3832', N'Compensation & Fines'),
        ('3833', N'Bad Debts Written-off'),
        ('3834', N'Special Service Expenses'),
        ('3835', N'Marriage Advances Amortization'),
        ('3836', N'Facility Share in Public Supplies'),
        ('3837', N'Free Goods & Services'),
        -- 384x Taxes & Fees
        ('3841', N'Production Fees'),
        ('3842', N'Other Taxes & Fees'),
        -- 385x Subsidies
        ('3851', N'Internal Subsidies'),
        ('3852', N'External Subsidies'),
        -- 411x Extractive Revenue
        ('4111', N'Net Sales'),
        ('4112', N'Change in Finished Production Inventory'),
        ('4113', N'Change in Work-in-Progress Inventory'),
        -- 412x Manufacturing Revenue
        ('4121', N'Net Sales'),
        ('4122', N'Change in Finished Production Inventory'),
        ('4123', N'Change in Work-in-Progress Inventory'),
        -- 413x Construction
        ('4131', N'Completed Quantities Revenue'),
        ('4132', N'Change in Work-in-Progress'),
        -- 414x Plant Production
        ('4141', N'Net Sales'),
        ('4142', N'Change in Finished Production Inventory'),
        ('4143', N'Standing Crops'),
        -- 415x Animal Production
        ('4151', N'Net Sales'),
        ('4152', N'Change in Finished Production Inventory'),
        ('4153', N'Change in Work-in-Progress Inventory'),
        -- 416x Utilities Revenue
        ('4161', N'Water Revenue'),
        ('4162', N'Electricity Revenue'),
        -- 438x Asset Rentals Revenue
        ('4382', N'Building Rental Revenue'),
        ('4383', N'Machinery & Equipment Rental Revenue'),
        -- 481x Transfer Revenue
        ('4811', N'Pension & Social Security Contributions'),
        ('4812', N'Social Security Share in Facility Profits'),
        ('4821', N'Public Treasury Grant'),
        ('4822', N'Grants from Central or Subsidiary Units'),
        -- 483x
        ('4831', N'Donations Received'),
        ('4832', N'Compensation & Fines Received'),
        ('4833', N'Previously Written-off Debts'),
        -- Level 5 sub-leaves
        ('11111', N'Purchase Cost'),
        ('11112', N'Reclamation Cost'),
        ('11231', N'Wells'),
        ('11233', N'Quarries'),
        ('11281', N'Railway Lines'),
        ('11282', N'Port Quays & Berths'),
        ('11283', N'Airport Runways'),
        ('11291', N'Sewage Systems'),
        ('11292', N'Water Reservoirs'),
        ('11293', N'Greenhouses'),
        ('11294', N'Water Pipelines'),
        ('11295', N'Electricity & Telephone Lines'),
        ('11411', N'Passenger Vehicles'),
        ('11412', N'Cargo Vehicles'),
        ('11413', N'Other Transport Vehicles'),
        ('12111', N'Purchase Cost (UC)'),
        ('12112', N'Reclamation Cost (UC)'),
        ('12241', N'Wells (UC)'),
        ('12242', N'Mines (UC)'),
        ('12243', N'Quarries (UC)'),
        ('12281', N'Railway Lines (UC)'),
        ('12282', N'Port Quays & Berths (UC)'),
        ('33431', N'Travel & Delegation for Training/Study'),
        ('33432', N'Travel & Delegation for Activity'),
        ('33611', N'Internal Subscriptions & Memberships'),
        ('33612', N'External Subscriptions & Memberships'),
        ('33671', N'Student & Trainee Allowances'),
        ('33672', N'Training & Study Fees'),
        ('33682', N'Audit Fees'),
        ('38371', N'Free Goods & Services Granted by Legislation'),
        ('38372', N'Free Goods & Services Granted by Management Decision')
    ) AS v(Code, NameEn)
)
UPDATE a SET a.NameEn = m.NameEn, a.UpdatedAt = SYSUTCDATETIME(), a.UpdatedBy = ISNULL(a.UpdatedBy, N'system')
FROM [acc].[Accounts] a JOIN m ON LTRIM(RTRIM(a.Code)) = m.Code
WHERE (a.NameEn IS NULL OR LTRIM(RTRIM(a.NameEn)) = N'');
SELECT @@ROWCOUNT AS Updated;
