// <auto-generated />
using System;
using IraqiTradeCenterCompany.API.Auth;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IraqiTradeCenterCompany.API.Auth.Migrations;

[DbContext(typeof(AuthDbContext))]
[Migration("20260218110000_AddCompanySettingsExchangeRatesJson")]
partial class AddCompanySettingsExchangeRatesJson
{
}
